### ISSUE TITLE
Random 1:1 video pairings

### ISSUE THREAD

**Issue by raphaelm** [venueless/venueless#160]
First work in #159 

## TODO

- [x] protocol docs
- [x] multi server support
- [x] authenticated janus connection
- [ ] better matching algorithm (no race conditions, don't give me the same person twice)
- [ ] Resolve all the TODOs in the cod
- [x] allow to mute
- [ ] test in more browsers
- [ ] handle all the error cases
- [x] show display name and profile picture of other person
- [ ] handle correctly if the other person hangs up
- [ ] make it pretty
- [ ] refactor the client side code so it can run in the background like our bbb rooms and stages?
- [x] respect globally silenced user state
- [ ] remove abandoned 1-user sessions
- [x] do not connect to blocked users
- [ ] support STUN/TURN
- [ ] tests for server-side code

optionally:

- [x] allow to select audio devices
- [ ] provide a good way to connect with the other person later on
- [ ] add a configurable maximum call time
- [ ] screen sharing?

and probably much more.

**Comment by rasos** [comment]
How about offering 1:1 rooms as breakout rooms in BBB? We run BBB 2.3 with up to 50 breakout rooms (config change).

**Comment by raphaelm** [comment]
I don't quite see your point, we have a feature for this now, and if you want to use BBB this way, sure, feel free to
